disabled_plugins = []
imports = []
oom_score = 0
plugin_dir = ""
required_plugins = []
root = "C:\\ProgramData\\containerd\\root"
state = "C:\\ProgramData\\containerd\\state"
temp = ""
version = 3

[cgroup]
path = ""

[debug]
address = ""
format = ""
gid = 0
level = ""
uid = 0

[grpc]
address = "\\\\.\\pipe\\containerd-containerd"
gid = 0
max_recv_message_size = 16777216
max_send_message_size = 16777216
tcp_address = ""
tcp_tls_ca = ""
tcp_tls_cert = ""
tcp_tls_key = ""
uid = 0

[metrics]
address = ""
grpc_histogram = false

[plugins]

[plugins."io.containerd.cri.v1.images"]
disable_snapshot_annotations = false
discard_unpacked_layers = false
image_pull_progress_timeout = "5m0s"
image_pull_with_sync_fs = false
max_concurrent_downloads = 3
snapshotter = "windows"
stats_collect_period = 10

[plugins."io.containerd.cri.v1.images".image_decryption]
key_model = "node"

[plugins."io.containerd.cri.v1.images".pinned_images]
sandbox = "registry.k8s.io/pause:3.9"

[plugins."io.containerd.cri.v1.images".registry]
config_path = ""

[plugins."io.containerd.cri.v1.runtime"]
cdi_spec_dirs = []
device_ownership_from_security_context = false
disable_apparmor = false
disable_cgroup = false
disable_hugetlb_controller = false
disable_proc_mount = false
drain_exec_sync_io_timeout = "0s"
enable_cdi = false
enable_selinux = false
enable_unprivileged_icmp = false
enable_unprivileged_ports = false
ignore_deprecation_warnings = []
ignore_image_defined_volumes = false
max_container_log_line_size = 16384
netns_mounts_under_state_dir = false
restrict_oom_score_adj = false
selinux_category_range = 0
tolerate_missing_hugetlb_controller = false
unset_seccomp_profile = ""

[plugins."io.containerd.cri.v1.runtime".cni]
bin_dir = "C:\\Program Files\\containerd\\cni\\bin"
conf_dir = "C:\\Program Files\\containerd\\cni\\conf"
conf_template = ""
ip_pref = ""
max_conf_num = 1
setup_serially = false

[plugins."io.containerd.cri.v1.runtime".containerd]
default_runtime_name = "runhcs-wcow-process"
ignore_blockio_not_enabled_errors = false
ignore_rdt_not_enabled_errors = false

[plugins."io.containerd.cri.v1.runtime".containerd.runtimes]

[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runhcs-wcow-hypervisor]
base_runtime_spec = ""
cni_conf_dir = ""
cni_max_conf_num = 0
container_annotations = ["io.microsoft.container.*"]
pod_annotations = ["io.microsoft.virtualmachine.*"]
privileged_without_host_devices = false
privileged_without_host_devices_all_devices_allowed = false
runtime_path = ""
runtime_type = "io.containerd.runhcs.v1"
sandboxer = ""
snapshotter = ""

[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runhcs-wcow-hypervisor.options]
SandboxIsolation = 1
ScaleCpuLimitsToSandbox = true

[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runhcs-wcow-process]
base_runtime_spec = ""
cni_conf_dir = ""
cni_max_conf_num = 0
container_annotations = ["io.microsoft.container.*"]
pod_annotations = []
privileged_without_host_devices = false
privileged_without_host_devices_all_devices_allowed = false
runtime_path = ""
runtime_type = "io.containerd.runhcs.v1"
sandboxer = ""
snapshotter = ""

[plugins."io.containerd.gc.v1.scheduler"]
deletion_threshold = 0
mutation_threshold = 100
pause_threshold = 0.02
schedule_delay = "0s"
startup_delay = "100ms"

[plugins."io.containerd.grpc.v1.cri"]
disable_tcp_service = true
enable_tls_streaming = false
stream_idle_timeout = "4h0m0s"
stream_server_address = "127.0.0.1"
stream_server_port = "0"

[plugins."io.containerd.grpc.v1.cri".x509_key_pair_streaming]
tls_cert_file = ""
tls_key_file = ""

[plugins."io.containerd.image-verifier.v1.bindir"]
bin_dir = "C:\\ProgramData\\containerd\\root\\opt\\image-verifier\\bin"
max_verifiers = 10
per_verifier_timeout = "10s"

[plugins."io.containerd.internal.v1.opt"]
path = "C:\\ProgramData\\containerd\\root\\opt"

[plugins."io.containerd.internal.v1.tracing"]

[plugins."io.containerd.metadata.v1.bolt"]
content_sharing_policy = "shared"

[plugins."io.containerd.monitor.container.v1.restart"]
interval = "10s"

[plugins."io.containerd.nri.v1.nri"]
disable = false
disable_connections = false
plugin_config_path = "/etc/nri/conf.d"
plugin_path = "/opt/nri/plugins"
plugin_registration_timeout = "5s"
plugin_request_timeout = "2s"
socket_path = "/var/run/nri/nri.sock"

[plugins."io.containerd.runtime.v2.task"]
platforms = ["windows/amd64", "linux/amd64"]
sched_core = false

[plugins."io.containerd.service.v1.diff-service"]
default = ["windows", "windows-lcow"]

[plugins."io.containerd.service.v1.tasks-service"]
blockio_config_file = ""
rdt_config_file = ""

[plugins."io.containerd.tracing.processor.v1.otlp"]

[plugins."io.containerd.transfer.v1.local"]
config_path = ""
max_concurrent_downloads = 3
max_concurrent_uploaded_layers = 3

[stream_processors]

[stream_processors."io.containerd.ocicrypt.decoder.v1.tar"]
accepts = ["application/vnd.oci.image.layer.v1.tar+encrypted"]
args = [
  "--decryption-keys-path",
  "C:\\Program Files\\containerd\\ocicrypt\\keys",
]
env = [
  "OCICRYPT_KEYPROVIDER_CONFIG=C:\\Program Files\\containerd\\ocicrypt\\ocicrypt_keyprovider.conf",
]
path = "ctd-decoder"
returns = "application/vnd.oci.image.layer.v1.tar"

[stream_processors."io.containerd.ocicrypt.decoder.v1.tar.gzip"]
accepts = ["application/vnd.oci.image.layer.v1.tar+gzip+encrypted"]
args = [
  "--decryption-keys-path",
  "C:\\Program Files\\containerd\\ocicrypt\\keys",
]
env = [
  "OCICRYPT_KEYPROVIDER_CONFIG=C:\\Program Files\\containerd\\ocicrypt\\ocicrypt_keyprovider.conf",
]
path = "ctd-decoder"
returns = "application/vnd.oci.image.layer.v1.tar+gzip"

[timeouts]
"io.containerd.timeout.bolt.open" = "0s"
"io.containerd.timeout.metrics.shimstats" = "2s"
"io.containerd.timeout.shim.cleanup" = "5s"
"io.containerd.timeout.shim.load" = "5s"
"io.containerd.timeout.shim.shutdown" = "3s"
"io.containerd.timeout.task.state" = "2s"

[ttrpc]
address = ""
gid = 0
uid = 0
