# - pipewire
audio_server = "pipewire"

# - firefox
browser = "firefox"

# - helix
editor = "helix"

# - thunar
file_manager = "thunar"

# - vscode
visual = "vscode"

# - hyprland
# - sway
window_manager = "sway"
