# - rofi
app_launcher = "rofi"

# - flexasio
asio_driver = "flexasio"

# - pipewire
# - voicemeeter
audio_server = "pipewire"

# - chrome
# - firefox
browser = "firefox"

# - helix
editor = "helix"

# - nautilus
# - thunar
file_manager = "nautilus"

# - dunst
notification_agent = "dunst"

# - alacritty
# - windows_terminal
term = "alacritty"

# - vscode
visual = "vscode"

# - hyprland
# - sway
window_manager = "sway"
